### PR TITLE
Added Dark Mode Toogle

### PR DESCRIPTION
**Pull request by ayushi-ras**
solved the issue #3

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@ayushi-ras Hi Ayushi it's great to have that toggle but try to change the font's colour into white after switching to dark mode & can u just change the icon cuz it's looking bit bulky. Do this, I'll merge this.

**Comment by ayushi-ras** [comment]
>ok sire

**Comment by Zack-Dx** [comment]
> > ok sire

ya tag me once done.

**Review by ayushi-ras — COMMENTED** [review]
Made the respective changes @Zack-Dx

**Comment by Zack-Dx** [comment]
@ayushi-ras Amazing work loved the transition. I'm merging this but I'd want to change the colour of the moon if possible to something else which's bright then throw a new pr if u can!

**Comment by ayushi-ras** [comment]
ok sure @Zack-Dx

**Pull request merged**
