### PR TITLE
enhance burger menu and logo

### PR DESCRIPTION
**Pull request by yskooo**
migrated from png to svg

### CODE REVIEW

**Comment by yskooo** [comment]
please add hacktoberfest

**Comment by Zack-Dx** [comment]
@yskooo 
Screenshot 2022-10-07 at 12 20 33 PM
Fix

**Comment by Zack-Dx** [comment]
and download button isn't visible on hamburger menu!

**Comment by yskooo** [comment]
I do not know that one yet lol

**Pull request closed without merging**
