### PR TITLE
updated logos

### PR DESCRIPTION
**Pull request by TaufeeqRiyaz**

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@TaufeeqRiyaz Hey! can u please change the download icon for buttons. It doesn't matches with the text in it.

**Comment by TaufeeqRiyaz** [comment]
1. updated discord logos
2. added download icon to buttons
3. updated readme.md
4. updated script.js to show "download for android"
5.

**Comment by TaufeeqRiyaz** [comment]
> @TaufeeqRiyaz Hey! can u please change the download icon for buttons. It doesn't matches with the text in it.

sure!

**Comment by Zack-Dx** [comment]
> > @TaufeeqRiyaz Hey! can u please change the download icon for buttons. It doesn't matches with the text in it.
> 
> sure!

once done! tag me

**Comment by TaufeeqRiyaz** [comment]
> > > @TaufeeqRiyaz Hey! can u please change the download icon for buttons. It doesn't matches with the text in it.
> > 
> > 
> > sure!
> 
> once done! tag me
@Zack-Dx 
please check now :)

**Pull request merged**
