### PR TITLE
Created and Added Discord Nitro page

### PR DESCRIPTION
**Pull request by THE-AryanKumar**
Added responsive Discord Nitro page. Plz review and approve...

### CODE REVIEW

**Comment by Zack-Dx** [comment]
@THE-AryanKumar Hi Aryan u did an amazing work but a cute mistake too. U didn't link your nitro page to the Home Page just add it. I'll merge this.

**Comment by THE-AryanKumar** [comment]
Oops!! Now check It out.... @Zack-Dx

**Comment by Zack-Dx** [comment]
@THE-AryanKumar Congrats! it's merged!

**Comment by THE-AryanKumar** [comment]
Can you close #147 issue and approve. Its still showing NOT-ACCEPTED
Thank You...

**Comment by Zack-Dx** [comment]
@THE-AryanKumar Aryan its having bit issue 
Screenshot 2022-10-08 at 4 10 16 PM
can u please fix this.

**Comment by THE-AryanKumar** [comment]
Its Working fine on me..., Can you pls check it from live server

**Comment by Zack-Dx** [comment]
> Its Working fine on me..., Can you pls check it from live server
> 
> 

it'll work fine for locals. But u need to set the directory properly to read else it can't get hosted.

**Pull request merged**
