### PR TITLE
Added the Open to Discord link

### PR DESCRIPTION
**Pull request by srummanf**
The open to browser tag was missing which is added now!

### CODE REVIEW

**Comment by TaufeeqRiyaz** [comment]
open to discord should take to "https://discord.com/app"

**Comment by srummanf** [comment]
Okay!!

**Comment by Zack-Dx** [comment]
> open to discord should take to "https://discord.com/app"

@TaufeeqRiyaz Right @srummanf Please fix that and throw a new pr.

**Comment by TaufeeqRiyaz** [comment]
> > open to discord should take to "https://discord.com/app"
> 
> @TaufeeqRiyaz Right @srummanf Please fix that and throw a new pr.

@Zack-Dx done, PR #112

**Comment by srummanf** [comment]
Okayy !!!

**Pull request closed without merging**
