### PR TITLE
Solved the download icon issue

### PR DESCRIPTION
**Pull request by Shivangbhatnagar237**
Fixed the alignment of the download icon.
changes
I reduced the padding and added flex to the download-button div

### CODE REVIEW

**Comment by Zack-Dx** [comment]
> Fixed the alignment of the download icon. changes I reduced the padding and added flex to the download-button div

this's amazing. I want you to do the same for the one in the bottom of the page.I'll merge this

**Comment by Shivangbhatnagar237** [comment]
changes2
Did these changes and here's the output on the second image
changes2out

**Comment by Zack-Dx** [comment]
@Shivangbhatnagar237 Thank you so much Shivam. Share love by giving a star to the repo. Merged!

**Comment by Shivangbhatnagar237** [comment]
@Zack-Dx Hey! can you please add the hacktoberfest-accepted label to this PR? Thanks

**Comment by Shivangbhatnagar237** [comment]
### @Zack-Dx Hey! can you please add the hacktoberfest-accepted label to this PR? Thanks
hack1

**Pull request merged**
